### PR TITLE
Respond with HTML too

### PR DESCRIPTION
**Pull request by btmills**
I *think* this is the reason the homepage wasn't showing.

### CODE REVIEW

**Comment by maxdignan** [comment]
Does this make it work on your local machine when you have this line changed? If so, that will be great, because that change will not interfere with what we've done on backend.

**Comment by btmills** [comment]
I'm guessing this is the error that was showing up on the home page and will fix that too, but at the very least it unlocks front end dev (tested the fix on two separate machines).

**Comment by maxdignan** [comment]
ok. go ahead and look at the current code on the github repo. Brad made some changes to it, and i think that those would solve this issue as well + there already up there

**Comment by btmills** [comment]
Yup, just saw that. This is now unnecessary.

**Comment by maxdignan** [comment]
gotcha, cool

**Pull request closed without merging**
